import type { EventRecord } from '@/types/event'
import { MOCK_ORGANISATIONS } from '@/lib/mock-organisations'

export const MOCK_EVENTS: EventRecord[] = [
  {
    id: 'evt-1',
    status: 'published',
    createdAt: '20/07/2026 09:00:00',
    updatedAt: '02/08/2026 10:15:00',
    form: {
      metadata: {
        registrationRequired: true,
        registrationUrl: 'https://events.civicdataspace.in/summit-2026',
        registrationEndDate: '2026-09-10',
        registrationEndTime: '23:59',
        title: 'Open Data Summit 2026',
        subtitle: 'Building Trusted Public Data Ecosystems for Better Governance',
        eventType: 'conference',
        theme: 'urban-development',
        overview:
          'A two-day summit bringing together civic technologists, government data officers, and researchers to discuss trusted, interoperable public data ecosystems.',
        startDate: '2026-09-18',
        startTime: '09:00',
        endDate: '2026-09-19',
        endTime: '17:00',
        accessType: 'hybrid',
        venueName: 'India Habitat Centre',
        address: 'Lodhi Road',
        city: 'New Delhi',
        state: 'Delhi',
        country: 'India',
        coverImage: null,
      },
      organisers: [MOCK_ORGANISATIONS[0]],
      partners: [MOCK_ORGANISATIONS[1], MOCK_ORGANISATIONS[2]],
      speakerCount: '12',
      publications: [],
      relatedContent: { datasets: [], useCases: [], collaboratives: [], aiModels: [] },
    },
  },
  {
    id: 'evt-2',
    status: 'published',
    createdAt: '10/07/2026 09:00:00',
    updatedAt: '28/07/2026 14:40:00',
    form: {
      metadata: {
        registrationRequired: true,
        registrationUrl: 'https://events.civicdataspace.in/ai-workshop',
        registrationEndDate: '2026-08-11',
        registrationEndTime: '18:00',
        title: 'AI for Public Good Workshop',
        subtitle: 'Practical approaches to responsible AI in public services',
        eventType: 'workshop',
        theme: 'health',
        overview:
          'A hands-on workshop covering practical, responsible approaches to deploying AI in public service delivery, with case studies and open discussion.',
        startDate: '2026-08-12',
        startTime: '10:00',
        endDate: '2026-08-12',
        endTime: '13:00',
        accessType: 'online',
        venueName: '',
        address: '',
        city: '',
        state: '',
        country: '',
        coverImage: null,
      },
      organisers: [MOCK_ORGANISATIONS[0]],
      partners: [],
      speakerCount: '4',
      publications: [],
      relatedContent: { datasets: [], useCases: [], collaboratives: [], aiModels: [] },
    },
  },
  {
    id: 'evt-3',
    status: 'published',
    createdAt: '01/07/2026 09:00:00',
    updatedAt: '15/07/2026 11:20:00',
    form: {
      metadata: {
        registrationRequired: true,
        registrationUrl: 'https://events.civicdataspace.in/meetup',
        registrationEndDate: '2026-07-25',
        registrationEndTime: '18:00',
        title: 'Civic Data Community Meetup',
        subtitle: 'Connecting practitioners working with public data',
        eventType: 'meetup',
        theme: 'urban-development',
        overview:
          'An informal meetup for practitioners across government, civil society, and research to share what they are building with public data.',
        startDate: '2026-07-30',
        startTime: '17:30',
        endDate: '2026-07-30',
        endTime: '20:00',
        accessType: 'in-person',
        venueName: 'CivicDataLab Office',
        address: 'Indiranagar',
        city: 'Bengaluru',
        state: 'Karnataka',
        country: 'India',
        coverImage: null,
      },
      organisers: [MOCK_ORGANISATIONS[0]],
      partners: [],
      speakerCount: '3',
      publications: [],
      relatedContent: { datasets: [], useCases: [], collaboratives: [], aiModels: [] },
    },
  },
  {
    id: 'evt-4',
    status: 'draft',
    createdAt: '28/06/2026 09:00:00',
    updatedAt: '05/07/2026 16:05:00',
    form: {
      metadata: {
        registrationRequired: false,
        registrationUrl: '',
        registrationEndDate: '',
        registrationEndTime: '',
        title: 'Data Governance Roundtable',
        subtitle: 'A closed discussion on responsible public data governance',
        eventType: 'roundtable',
        theme: 'urban-development',
        overview:
          'A closed-door roundtable with policy makers and data stewards to discuss responsible governance frameworks for shared public data.',
        startDate: '2026-07-05',
        startTime: '11:00',
        endDate: '2026-07-05',
        endTime: '13:00',
        accessType: 'in-person',
        venueName: 'Delhi Policy Group',
        address: '',
        city: 'New Delhi',
        state: 'Delhi',
        country: 'India',
        coverImage: null,
      },
      organisers: [MOCK_ORGANISATIONS[0]],
      partners: [],
      speakerCount: '',
      publications: [],
      relatedContent: { datasets: [], useCases: [], collaboratives: [], aiModels: [] },
    },
  },
]
